server:
  port: 51071
spring:
  application:
    ## 注册服务名
    name: admin-order
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 200MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  messages:
    basename: i18n/messages
    encoding: utf-8
  # redis 配置
